14 sprint: add-bookings
HoneyVanity/ShareIt pull request #2
Opened 2023-07-28 01:01 UTC by HoneyVanity

2023-07-28 17:33 UTC, NikolaiDem requested changes

2023-07-28 17:33 UTC, NikolaiDem commented on .idea/compiler.xml
>          <sourceOutputDir name="target/generated-sources/annotations" />
Файлы из .idea в коммите лишние

2023-07-28 17:33 UTC, NikolaiDem commented on shareit/src/main/java/ru/yandex/practicum/shareit/booking/Booking.java
> +@Data
В Data находятся equals и hashCode, которые переопределять для класса модели нет необходимости.
Аналогично для остальных моделей

2023-07-28 17:33 UTC, NikolaiDem commented on shareit/src/main/java/ru/yandex/practicum/shareit/booking/BookingService.java
> +
Еще лучше проверить, что вещь не забронирована никем другим на запрашиваемые даты.

2023-07-28 17:33 UTC, NikolaiDem commented on shareit/src/main/java/ru/yandex/practicum/shareit/item/service/ItemService.java
> +                    List<Booking> bookings = bookingRepo.findAllByItemIdOrderByStartAsc(item.getId());
Лучше получить бронирования для всех items сразу, чтобы не обращаться к бд в каждой итерации (проблема N+1 запроса).
Аналогично для комментариев

2023-07-28 17:33 UTC, NikolaiDem commented on shareit/src/main/java/ru/yandex/practicum/shareit/user/service/UserService.java
> +        //checkIfEmailHasDuplicates(dto.getEmail());
Почему закомментировано?)

2023-07-29 17:16 UTC, HoneyVanity commented on shareit/src/main/java/ru/yandex/practicum/shareit/booking/Booking.java
> +@Data
без @Data у сущности Comment падает Mapstruct library

2023-07-29 17:19 UTC, HoneyVanity commented on shareit/src/main/java/ru/yandex/practicum/shareit/user/service/UserService.java
> +        //checkIfEmailHasDuplicates(dto.getEmail());
Забыла убрать

2023-07-30 06:34 UTC, NikolaiDem requested changes

2023-07-30 06:34 UTC, NikolaiDem commented on shareit/src/main/java/ru/yandex/practicum/shareit/item/service/ItemService.java
> +        List<Comment> comments = commentRepo.findAll();
Выгружать нужно не все комментарии, а связанные с текущими items.
Аналогично для bookings

2023-07-30 06:34 UTC, NikolaiDem commented on shareit/src/main/java/ru/yandex/practicum/shareit/item/service/ItemService.java
> +                    if (list.stream().anyMatch(b -> b.getItem().getId().equals(item.getId()))) {
Чтобы для каждого item не перебирать весь list, лучше list преобразовать в Map<Long, List<Bookings>> bookingsByItem. И за O(1) можно сразу по ключу получить все бронирования.
Аналогично для комментариев.

2023-07-30 06:34 UTC, NikolaiDem commented on shareit/src/main/java/ru/yandex/practicum/shareit/booking/BookingService.java
> +            boolean isNotIntersection = bookings.stream()
boolean isNotIntersection = bookings.stream()
                    .allMatch(b -> !booking.getStart().isBefore(b.getEnd()) ||
                            !booking.getEnd().isAfter(b.getStart()));

2023-07-30 21:10 UTC, NikolaiDem requested changes

2023-07-30 21:10 UTC, NikolaiDem commented on shareit/src/main/java/ru/yandex/practicum/shareit/item/service/ItemService.java
> +        Map<Long, Booking> bookingsByItem = bookingRepo
От такого преобразования ничего не поменялось)
Имелось ввиду 
        Map<Long, List<Comment>> commentsByItem = commentRepo
                .findAllByItem_Owner_Id(userId)
                .stream()
                .collect(Collectors.groupingBy(
                        comment -> comment.getItem().getId()));

        Map<Long, List<Booking>> bookingsByItem = bookingRepo
                .findAllByItemOwnerIdOrderByStartDesc(userId)
                .stream()
                .collect(Collectors.groupingBy(
                        booking -> booking.getItem().getId()));

        List<Item> items = repo.findAllByOwnerId(userId).stream()
                .peek(item -> {
                    List<Booking> bookings = bookingsByItem.getOrDefault(item.getId(), Collections.emptyList());
                    item.setNextBooking(bookingMapper.toShortBookingDto(getNextBooking(bookings)));
                    item.setLastBooking(bookingMapper.toShortBookingDto(getLastBooking(bookings)));
                })
                .peek(item -> item.setComments(commentsByItem.getOrDefault(item.getId(), Collections.emptyList())
                        .stream()
                        .map(commentMapper::toCommentDto)
                        .collect(Collectors.toList())))
                .collect(Collectors.toList());

2023-07-30 21:10 UTC, NikolaiDem commented on shareit/src/main/java/ru/yandex/practicum/shareit/booking/BookingService.java
> +            boolean isNotIntersection = bookings.stream()
Пусть существующие бронирования
1) с 10:00 до 13:00
2) с 07:00 до 09:00
Новое бронирование с 06:00 до 08:00 (booking)
По существующей логике 06:00.isBefore(13:00) - это true
И получаем отсутствие пересечений, хотя второе бронирование будет пересекаться с booking

2023-07-31 15:16 UTC, NikolaiDem approved these changes

2023-07-31 15:16 UTC, NikolaiDem commented on shareit/src/main/java/ru/yandex/practicum/shareit/booking/BookingService.java
> +                            booking.getEnd().isBefore(b.getStart())) ||
Если booking.getEnd().isBefore(b.getStart()) true, то booking.getStart().isBefore(b.getStart()) тоже true автоматически.
Аналогично для второго условия

2023-07-31 22:59 UTC, closed without merging